# Generated by Django 6.0.1 on 2026-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('bus', 'seat_number')},
        ),
    ]
